myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ots/',include('ots.urls')),
]

ots/urls.py
from django.urls import path
from ots.views import *
app_name='ots'

urlpatterns=[
    path('',welcome),
    path('new-candidate',candidateRegistrationForm,name='registrationform'),
    path('storecandidate',candidateRegistration,name="storeCandidate"),
    path('login',loginview,name='login'),
    path('home',candidatehome,name='home'),
    path('test-paper',testpaper,name='testpaper'),
    path('calculate-result',calculateTestResult,name='calculateTest'),
    path('tes-history',testResultHistory,name='testHistory'),
    path('result',showTestResult,name='result'),
    path('logout',logoutView,name='logout'),



]

ots/models.py
from django.db import models

# Create your models here.
class Candidate(models.Model):
    username=models.CharField(primary_key=True,max_length=50)
    password=models.CharField(null=False,max_length=20)
    name=models.CharField(null=False,max_length=30)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0)
    
    def __str__(self):
        return self.username

class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)

    def __str__(self):
        return self.que

class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()
    

ots/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from ots.models import *
from django.template import loader
import random
# Create your views here.

def welcome(req):
    template=loader.get_template('welcom.html')
    return HttpResponse(template.render())
    # pass

def candidateRegistrationForm(req):
    res=render(req,'registration_form.html')
    return res

def candidateRegistration(req):
    if req.method=='POST':
        username=req.POST['username']
        #check if the user alredy exist
        if(len(Candidate.objects.filter(username=username))):
            userstatus=1
        else:
            candidate=Candidate()
            candidate.username=username
            candidate.password=req.POST['password']
            candidate.name=req.POST['name']
            candidate.save()
            userstatus=2
    else:
        userstatus=3 # if request is not post
    context={
        'userstatus':userstatus,
    }
    res=render(req,'registration.html',context)
    return res


def loginview(req):
    # pass
    # template=loader.get_template('nig.html')
    # return HttpResponse(template.render())
    if req.method=='POST':
        username=req.POST['username']
        password=req.POST['password']
        candidate=Candidate.objects.filter(username=username,password=password)
        if(len(candidate)==0):
            loginError='Invalid Username or password'
            res=render(req,'login.html',{'loginError':loginError})
        else:
            #login Succcess
            req.session['username']=candidate[0].username
            req.session['name']=candidate[0].name
            res=HttpResponseRedirect('home')
    else:
        res=render(req,'login.html')
            

    return res

def candidatehome(req):
    # pass
    if ('name' not in req.session.keys()):
        res=HttpResponseRedirect('login')
    else:
        numbers=range(1,11)
        context={'num':numbers}
        res=render(req,'home.html',context)
    return res


def testpaper(req):
    if ('name' not in req.session.keys()):
        res=HttpResponseRedirect('login')
    # fetch quesstions from dbs
    n=int(req.GET['n'])
    question_pool=list(Question.objects.all())
    random.shuffle(question_pool)
    questions_list=question_pool[:n]

    context={'questions':questions_list}
    res=render(req,'test_paper.html',context)
    return res
    

def calculateTestResult(req):
    if ('name' not in req.session.keys()):
        res=HttpResponseRedirect('login')
        return res
    
    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]

    # accessing params

    for k in req.POST:
        if k.startswith('qno'):
            qid_list.append(int(req.POST[k]))
    
    print(qid_list)
        
    for n in qid_list:
        question=Question.objects.get(qid=n)
        print("Correct:", question.ans, "User ans:",req.POST['q'+str(n)] )
        try:
            if question.ans == req.POST['q'+str(n)]:
                total_right+=1
            else:
                # total_wrong+=1
                total_wrong=total_wrong+1
            
            total_attempt+=1
        except:
            pass
    points=(total_right-total_wrong)/len(qid_list)*10
        # store result in Result table
    result=Result()
    result.username=Candidate.objects.get(username=req.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()

    #updating candidate table
    candidate=Candidate.objects.get(username=req.session['username'])
    candidate.test_attempted+=1
    candidate.points=((candidate.test_attempted-1+points)/candidate.test_attempted)
    candidate.save()
    return HttpResponseRedirect('result')

def showTestResult(req):
    if ('name' not in req.session.keys()):
        res=HttpResponseRedirect('login')
        return res
    #fetch latest result from result table
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid,username=req.session['username'])
    context={'result':result}
    res=render(req,'show_result.html',context)
    return res

def testResultHistory(req):
    if ('name' not in req.session.keys()):
        res=HttpResponseRedirect('login')
        return res
    
    candidate=Candidate.objects.filter(username=req.session['username'])
    results=Result.objects.filter(username=candidate[0].username)
    context={'candidate':candidate[0],'results':results}
    res=render(req,"candidate_history.html",context)
    return res
    



def logoutView(req):
    if ('name' in req.session.keys()):
        del req.session['username']
        del req.session['name']
        res=HttpResponseRedirect('login')
    return res

ots/templates/candidate_history.html
{% extends "main.html" %}

{% block title %}
Pariksha -Test History {% endblock %}

{% block top %}
<a href="{%url 'ots:home' %}">Home</a>
<a href="{%url 'ots:logout' %}">Logout</a>
{% endblock %}

{% block content %}
    <h1>Your report Card</h1>
    <h3>Hi <span class="special">{{candidate.name}}</span>,you have attempted in total <span class="special">{{candidate.test_attempted}} </span>  tests  and the yor overall score is <span class="special">{{candidate.points}} </span> on the scale of 10 </h3>
    <table>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Attempt</th>
            <th>Right</th>
            <th>Wrong</th>
            <th>Points</th>
        </tr>

        {% for r in results %}
            <tr>
                <td>{{r.date}}</td>
                <td>{{r.time}} </td>
                <td>{{r.attempt}}</td>
                <td>{{r.right}}</td>
                <td>{{r.wrong}}</td>
                <td>{{r.points}}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

ots/templates/home.html
{% extends "main.html" %}

{% block title %}
    Pariksha-Candidate Home Page
{% endblock %}


{% block top %}
    <div class="top-link">
        
        <a href="{%url 'ots:logout' %}">Logout</a>

    </div>
   
{% endblock %}

{% block content %}
<h1>Welcome <span class="special">{{request.session.name}}</span> , to your home page</h1>
{% for i in num %}
    <div class="button-link">
        <a href="{% url 'ots:testpaper' %}?n={{i}}">Test Of {{i}} Question</a>

    </div>

{% endfor %}
    
    <div class="b-link">
        <a href="{% url 'ots:testHistory' %}">Test History</a>
    </div>
{% endblock %}

ots/templates/login.html
{% extends "main.html" %}

{% block title %}
Pariksha-Login Form
{% endblock %}

{% block top %}
<a href="{%url 'ots:registrationform' %}">SignUp </a>

{% endblock %}

{% block content %}
<h1 >Login Form</h1>
    <div class="all-forms">
        {% if loginError %}
            <div id="error">
                {{ loginError }}
            </div>
        {% endif %}
        <form action="{% url 'ots:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-unit">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username">
            </div> 
            <div class="form-unit">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password">
            </div>
            <div class="form-unit">
                <button type="submit">Login</button>
                <button type="reset">Reset</button>
            </div>
            
        </form>
        <h4>New User ? <a href="{%url 'ots:registrationform' %}">SignUp </a> </h4>
    </div>

{% endblock %}

ots/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <link rel="stylesheet" href="{% static 'formstyle.css' %}">
    <link rel="stylesheet" href="{% static 'buttonstyle.css' %}">
    
    
</head>
<body>
    <div class="top">
        <div class="sitename">
            <h1>Pariksha [Online Quiz System]</h1>
        </div>
        <div class="menu">
            {% block top %}
            {% endblock %}
        </div>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

ots/templates/registration.html
{% extends "main.html" %}

{% block title %}
Pariksha-Registration status
{% endblock %}

{% block top %}
<a href="{%url 'ots:registrationform' %}">SignUp </a>
<a href="{%url 'ots:login' %}">Login</a>
{% endblock %}

{% block content %}
    {% if userstatus == 1 %}
     <div class="usersatus">
        <h2>Sorry, Username Already Exists </h2>
        <a href="{%url 'ots:registrationform' %}">SignUp Again</a>
     </div>
    {% elif userstatus == 2 %}
        <div class="usersatus">
            <h2>Congrats!!, User Created </h2>
            <a href="{%url 'ots:login' %}">Login</a>
        </div>
    {% elif userstatus == 3 %}
        <div class="usersatus">
             <h2>OPPS, Improper Request </h2>
            <a href="{%url 'ots:registrationform' %}">SignUp Again</a>
        </div>
       
    {% endif %}

{% endblock %}

ots/templates/registration_form.html
{% extends "main.html" %}

{% block title %}
Welocome to Pariksha Resgistration Form
{% endblock %}

{% block top %}

<!-- <a href="{%url 'ots:login' %}">Login</a> -->
{% endblock %}

{% block content %}

<div class="all-forms">
    <form action="{% url 'ots:storeCandidate' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" id="username">

        <label for="password">Password:</label>
        <input type="password" name="password" id="password">

        <label for="name">Name:</label>
        <input type="text" name="name" id="name">

        <button type="submit">Submit</button>
        <button type="reset">Reset</button>
    </form>

    <h3>Already Have an account,
        <a href="{%url 'ots:login' %}">Click Here</a>
    </h3>

</div>
{% endblock %}

ots/templates/show_result.html
{% extends "main.html" %}

{% block title %}
Pariksha -Test Result {% endblock %}

{% block top %}
<a href="{%url 'ots:home' %}">Home</a>
<a href="{%url 'ots:logout' %}">Logout</a>
{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Attempt</th>
            <th>Right</th>
            <th>Wrong</th>
            <th>Points</th>
        </tr>

        {% for r in result %}
            <tr>
                <td>{{r.date}}</td>
                <td>{{r.time}} </td>
                <td>{{r.attempt}}</td>
                <td>{{r.right}}</td>
                <td>{{r.wrong}}</td>
                <td>{{r.points}}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

ots/templates/test_paper.html
{% extends "main.html" %}

{% block title %}
    Pariksha- Test Paper
{% endblock %}

{% block top %}

{% endblock %}

{% block content %}
    <form action="{% url 'ots:calculateTest' %}" method="POST">
        {% csrf_token %}
        {% for question in questions %}
        <div class="full-que">
                <div class="question">
                <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}">
                <b>{{question.que}}</b>
                
            </div>
            <div class="options"><input type="radio" name="q{{question.qid}}" value="A">{{question.a}}</div>
            <div class="options"><input type="radio" name="q{{question.qid}}" value="B">{{question.b}}</div>
            <div class="options"><input type="radio" name="q{{question.qid}}" value="C">{{question.c}}</div>
            <div class="options"><input type="radio" name="q{{question.qid}}" value="D">{{question.d}}</div>

        </div>
        {% endfor %}


        <div>
           <!-- <input type="submit" value="submit"> -->
            <button type="submit">Submit</button>
        </div>

    </form>
{% endblock %}

ots/templates/welcom.html
{% extends "main.html" %}

{% block title %}
Welocome to Pariksha
{% endblock %}

{% block top %}
<a href="{%url 'ots:registrationform' %}">SignUp </a>
<a href="{%url 'ots:login' %}">Login</a>
{% endblock %}

{% block content %}

{% endblock %}